title: lume-simple-blog

description: A simple Lume blog template.

blurb: |
  A simple Lume blog template

mugshot: /img/lume.webp

author:
  name: you
  email: you@example.com

github: https://github.com/ghost

repo: https://github.com/joefg/lume-simple-blog

links:
  lume: https://lume.land/
  Simple.css: https://simplecss.org/
