title: lume-simple-blog
description: A simple Lume blog template.

author:
  name: you
  email: you@example.com

github: https://github.com/ghost

bulletin: This blog template is free, forever!

header:
  title: lume-simple-blog
  blurb: A simple Lume blog template
  mugshot: /img/lume.webp
  links:
    lume: https://lume.land/
    Simple.css: https://simplecss.org/

footer:
  text: Built with deno, lume, and Simple.css.
  repo: https://github.com/joefg/lume-simple-blog
  links:
    About: /
